"""empty message

Revision ID: 235a1d3e967f
Revises: 
Create Date: 2020-04-24 15:14:19.589253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235a1d3e967f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'name')
    # ### end Alembic commands ###
